{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "portfolio-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio-ui.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "portfolio-ui.selectorLabels" . | nindent 6 }}
      app: portfolio-ui
{{- end }}
